Prepare for testing

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -8,14 +8,12 @@ on:
   workflow_dispatch:
 
 jobs:
-  flatter:
-    name: Flatter
+  build:
+    name: Build bundle
     runs-on: ubuntu-latest
     container:
       image: ghcr.io/andyholmes/flatter/kde:5.15-22.08
       options: --privileged
-    outputs:
-      repository: ${{ steps.flatpak.outputs.repository }}
 
     strategy:
       matrix:
@@ -39,8 +37,8 @@ jobs:
           sed -i 's|branch: LinkMerge|tag: ${{github.ref_name}}|' $name.yaml
           url=https://github.com/realthunder/$name.BaseApp/releases/download/latest/$name
           if ! which wget; then yum install wget -y; fi
-          wget $url.BaseApp2.flatpak
-          flatpak install $name.BaseApp2.flatpak
+          wget $url.BaseApp3.flatpak
+          flatpak install -y $name.BaseApp3.flatpak
 
       - name: Build
         id: flatpak
@@ -50,7 +48,7 @@ jobs:
             org.freecadweb.FreeCAD.Link.yaml
           arch: ${{ matrix.arch }}
           upload-bundles: true
-          cache-key: FreeCAD-Link-${{ github.sha }}
+          cache-key: FreeCAD-Link
           flatpak-builder-args: |
             --install-deps-from=flathub
 
@@ -58,35 +56,37 @@ jobs:
   deploy:
     name: Deploy
     runs-on: ubuntu-latest
-    needs: flatter
+    needs: build
 
     steps:
       - name: Prepare assets
         run: |
-            tag=${{ github.ref_name }}
-            name=`echo ${{ needs.flatter.outputs.repository }}/*.flatpak`
-            mv $name ${name%.flatpak}-$tag.flatpak
-            echo "RELEASE_ASSETS=${name%.flatpak}"'*.flatpak' >> $GITHUB_ENV
-            case $tag in
-            *tip)
-                echo "RELEASE_NAME=Tip" >> $GITHUB_ENV
-                echo "IS_PRERELEASE=true" >> $GITHUB_ENV
-                branding=../conda/branding/asm3-daily
-                ;;
-            *edge)
-                echo "RELEASE_NAME=Edge" >> $GITHUB_ENV
-                echo "IS_PRERELEASE=true" >> $GITHUB_ENV
-                release=Edge
-                branding=../conda/branding/asm3-daily
-                ;;
-            *stable)
-                echo "RELEASE_NAME=$tag" >> $GITHUB_ENV
-                echo "IS_PRERELEASE=false" >> $GITHUB_ENV
-                ;;
-            *)
-                echo "Invalid tag"
-                exit 1
-            esac
+          set -x
+          name=org.freecadweb.FreeCAD.Link.BaseApp
+          mv $name*/*.flatpak .
+          name=`echo *.flatpak`
+          echo "RELEASE_ASSETS=$name" >> $GITHUB_ENV
+          tag=${{ github.ref_name }}
+          case $tag in
+          *tip)
+              echo "RELEASE_NAME=Tip" >> $GITHUB_ENV
+              echo "IS_PRERELEASE=true" >> $GITHUB_ENV
+              branding=../conda/branding/asm3-daily
+              ;;
+          *edge)
+              echo "RELEASE_NAME=Edge" >> $GITHUB_ENV
+              echo "IS_PRERELEASE=true" >> $GITHUB_ENV
+              release=Edge
+              branding=../conda/branding/asm3-daily
+              ;;
+          *stable)
+              echo "RELEASE_NAME=$tag" >> $GITHUB_ENV
+              echo "IS_PRERELEASE=false" >> $GITHUB_ENV
+              ;;
+          *)
+              echo "Invalid tag"
+              exit 1
+          esac
 
       - name: Delete old release assets
         uses: realthunder/delete-release-assets@v1
